# Generated by Django 2.1.3 on 2019-04-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvInfoPage', '0002_auto_20190424_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_genre',
            new_name='Tv_genre',
        ),
    ]
