# Generated by Django 2.1.3 on 2019-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvInfoPage', '0005_tv_details_tv_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_details',
            name='imdb_rating',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
